In [2]:
import numpy as np
import pandas as pd

In [3]:
# read the data (import file into local folder)
data = pd.read_csv('symptom_probabilities.csv')
data.head()

,diseases,anxiety and nervousness,depression,shortness of breath,depressive or psychotic symptoms,sharp chest pain,dizziness,insomnia,abnormal involuntary movements,chest tightness,...,stuttering or stammering,problems with orgasm,nose deformity,lump over jaw,sore in nose,hip weakness,back swelling,ankle stiffness or tightness,ankle weakness,neck weakness
0,abdominal aortic aneurysm,0.0,0.0,0.760870,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,abdominal hernia,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,abscess of nose,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,abscess of the lung,0.0,0.0,0.894737,1.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,abscess of the pharynx,0.0,0.0,0.000000,0.0,0.780059,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
# rows and columns in the dataset
data.shape

(773, 378)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 773 entries, 0 to 772
Columns: 378 entries, diseases to neck weakness
dtypes: float64(377), object(1)
memory usage: 2.2+ MB

In [6]:
#print(data.loc[2])

In [7]:
# select a row
# for this row, if theres any column with a value of 0, drop it
data = data.loc[772].replace(0, np.nan).dropna()

In [8]:
# show the name of the disease
data.head(1)

diseases    zenker diverticulum
Name: 772, dtype: object

In [9]:
# convert invalid values to NaN, sort numeric values from highest to lowest
data = pd.to_numeric(data, errors='coerce')
data = data.sort_values(ascending=False)

In [10]:
# get top 5 symptoms (if there is up to 5)
data.head(5)

sore throat         1.000000
elbow weakness      0.909091
sharp chest pain    0.818182
diseases                 NaN
Name: 772, dtype: float64

In [11]:
# all symptoms
print(data.to_markdown())

|                  |        772 |
|:-----------------|-----------:|
| sore throat      |   1        |
| elbow weakness   |   0.909091 |
| sharp chest pain |   0.818182 |
| diseases         | nan        |